apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "tms-frontend.fullname" . }}
  labels:
    {{- include "tms-frontend.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "tms-frontend.fullname" . }}
  port:
    targetPort: 80
  tls:
    termination: edge
  wildcardPolicy: None
